esphome:
  name: esp-leonid

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "uZ+KczecyzjIgUANwgKS/KhzMCK42cRz1ZRpF0+FX4w="

ota:
  password: "8bbd84e9e0aac75596473543cde99da9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp-Leonid Fallback Hotspot"
    password: "leonid2006"

captive_portal:
    
web_server:
  local: true
  auth:
    username: admin
    password: "12345678"

output:
  - platform: ledc
    pin: GPIO2
    id: gpio_2

  - platform: ledc
    pin: GPIO16
    id: gpio_16

light:
  - platform: monochromatic
    output: gpio_2
    name: "Light above the work area"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
  - platform: monochromatic
    output: gpio_16
    name: "General light"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
 
sensor:
  - platform: dht
    pin: GPIO 5
    temperature:
      name: "Garage temperature"
    humidity:
      name: "Humidity in the garage"
    update_interval: 60s

switch:
  - platform: gpio
    pin: GPIO 16
    name: "Garage door opening button"
    id: open_switch
  - platform: gpio
    pin: GPIO 4
    name: "Garage door closing button"
    id: close_switch
cover:
  - platform: template
    name: "Garage Door"
    open_action:
      - switch.turn_off: close_switch
      - switch.turn_on: open_switch
      - delay: 1s
      - switch.turn_off: open_switch
    close_action:
      - switch.turn_off: open_switch
      - switch.turn_on: close_switch
      - delay: 1s
      - switch.turn_off: close_switch
    stop_action:
      - switch.turn_off: close_switch
      - switch.turn_off: open_switch
    optimistic: true
    assumed_state: true

binary_sensor:
  - platform: gpio
    pin:
      number: 17
      inverted: true
    name: "Door opening sensor"
    device_class: motion
